# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-27 07:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210726_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 27, 10, 35, 27, 135428), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 27, 10, 35, 27, 136429), verbose_name='Дата'),
        ),
    ]
