# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-28 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210727_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 28, 10, 59, 7, 936612), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 28, 10, 59, 7, 936612), verbose_name='Дата'),
        ),
    ]
