# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-30 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210728_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 30, 16, 29, 16, 409956), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 30, 16, 29, 16, 410956), verbose_name='Дата'),
        ),
    ]
