# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-31 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210730_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 31, 13, 24, 40, 174068), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 31, 13, 24, 40, 174068), verbose_name='Дата'),
        ),
    ]
